typesense:
    restart: unless-stopped
    image: typesense/typesense:0.20.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    volumes:
      - ./data:/data
    ports:
      - 8108:8108