app:
    image: thecodingmachine/php:8.0-v4-apache-node12
    container_name: app
    volumes:
      - ./:/var/www/html:rw
    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_GD: 1
      PHP_INI_MEMORY_LIMIT: "1G"
      # STARTUP_COMMAND_1: "composer install"
      # STARTUP_COMMAND_2: "yarn watch"
    ports:
      - "80:80"
    networks:
      - PROJECT_FOLDER